# Generated by Django 6.0 on 2026-01-05 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='Variation_value',
            new_name='variation_value',
        ),
    ]
